@php
    $selectedRole = old('role', $target?->portalRole?->identifier ?? \App\Enums\PortalRoleIdentifier::SiteManager->value);
    $selectedCustomer = (string) old('customer_organisation_id', $target?->customer_organisation_id ?? $preselectedCustomer?->id ?? '');
    $selectedSites = array_map('strval', old('site_ids', $target?->assignedSites->pluck('id')->all() ?? ($preselectedSite ? [$preselectedSite->id] : [])));
@endphp
<x-layouts.portal :title="($target ? 'Edit User' : 'Add User').' | Fenster'" sidebar-label="Menu">
    @include('office.partials.support-styles')
    <div class="admin-workspace support-workspace"><a class="admin-back" href="{{ $target ? route('office.workspace.users.show', $target) : route('office.workspace.users.index') }}">← {{ $target?->name ?? 'Users' }}</a>
        <header><p class="eyebrow">User administration</p><h1 class="admin-title">{{ $target ? 'Edit User' : 'Add User' }}</h1><p class="admin-intro">External users belong to one customer and may have access to several sites for that customer.</p></header>
        @if ($errors->any())<div class="admin-error" role="alert"><h2 class="font-bold">Please check the form.</h2><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <form method="POST" action="{{ $target ? route('portal.office.users.update', $target) : route('portal.office.users.store') }}" class="admin-card max-w-3xl space-y-5" x-data="{ selectedRole: @js($selectedRole), selectedCustomer: @js($selectedCustomer) }">
            @csrf @if($target) @method('PATCH') <input type="hidden" name="lock_version" value="{{ $target->lock_version }}"> @endif
            <fieldset class="support-section space-y-5"><legend>Identity</legend><p class="support-hint">Use the name and email address this person will sign in with.</p><div class="support-grid">
            <div><label class="form-label" for="user-name">Name</label><input class="form-input" id="user-name" name="name" required maxlength="255" autocomplete="name" value="{{ old('name', $target?->name) }}"></div>
            <div><label class="form-label" for="user-email">Email</label><input class="form-input" id="user-email" name="email" type="email" required maxlength="255" autocomplete="email" value="{{ old('email', $target?->email) }}"></div>
            </div></fieldset><fieldset class="support-section space-y-5"><legend>Role and site access</legend><p class="support-hint">Choose a role, then a customer and the sites this person needs.</p>
            <div><label class="form-label" for="user-role">Role</label><select class="form-input" id="user-role" name="role" required x-model="selectedRole">@foreach($roles as $role)<option value="{{ $role->identifier }}">{{ $role->name }}</option>@endforeach</select></div>
            <p class="support-note" x-show="selectedRole === 'fenster_office_staff'">Global Office access. Office Staff can manage customers and review requests across all sites.</p>
            <div x-show="selectedRole !== 'fenster_office_staff'"><label class="form-label" for="user-customer">Customer</label><select class="form-input" id="user-customer" name="customer_organisation_id" x-model="selectedCustomer"><option value="">Select a customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }}{{ $customer->is_active ? '' : ' — inactive' }}</option>@endforeach</select></div>
            <fieldset x-show="selectedRole !== 'fenster_office_staff'" class="space-y-3"><legend class="form-label">Assigned Sites</legend><p class="support-note" x-show="!selectedCustomer">Select a customer above to see their sites.</p><p class="text-sm text-slate-600">Choose any sites this user needs. Leaving all unchecked gives the user no site access.</p>
                @foreach($customers as $customer)<div x-show="selectedCustomer === '{{ $customer->id }}'" class="rounded-lg border border-slate-200 p-3"><p class="font-bold">{{ $customer->name }}</p><div class="mt-2 grid gap-2 sm:grid-cols-2">@forelse($sites->where('customer_organisation_id', $customer->id) as $site)<label class="flex min-h-11 items-center gap-3 rounded border border-slate-200 px-3 py-2"><input class="h-5 w-5 rounded" type="checkbox" name="site_ids[]" value="{{ $site->id }}" :disabled="selectedCustomer !== '{{ $customer->id }}'" @checked(in_array((string)$site->id, $selectedSites, true))><span>{{ $site->name }}{{ $site->is_active ? '' : ' — inactive' }}</span></label>@empty<p class="text-sm text-slate-600">No sites exist for this customer.</p>@endforelse</div></div>@endforeach
            </fieldset>
            @if($target && $target->customer_organisation_id)<label x-show="(selectedRole === 'fenster_office_staff' && @js($target->portalRole?->identifier !== 'fenster_office_staff')) || (selectedRole !== 'fenster_office_staff' && selectedCustomer !== '{{ $target->customer_organisation_id }}')" class="admin-notice flex items-start gap-3"><input class="mt-1 h-5 w-5" type="checkbox" name="confirm_customer_change" value="1" @checked(old('confirm_customer_change'))><span><strong>Confirm customer change.</strong> Changing this user’s customer will remove access to sites belonging to the current customer.</span></label>@endif
            </fieldset><fieldset class="support-section space-y-5"><legend>Sign-in and account status</legend>
            <div><label class="form-label" for="user-password">{{ $target ? 'New password (optional)' : 'Temporary password' }}</label><input class="form-input" id="user-password" name="password" type="password" {{ $target ? '' : 'required' }} minlength="12" autocomplete="new-password"><p class="mt-2 text-sm text-slate-600">At least 12 characters with letters and numbers. Passwords are securely hashed and never shown again.</p></div>
            <div><label class="form-label" for="user-password-confirmation">Confirm password</label><input class="form-input" id="user-password-confirmation" name="password_confirmation" type="password" {{ $target ? '' : 'required' }} autocomplete="new-password"></div>
            @unless($target)<input type="hidden" name="is_active" value="0"><label class="flex min-h-11 items-center gap-3"><input class="h-5 w-5 rounded" type="checkbox" name="is_active" value="1" @checked(old('is_active', true))><span class="font-bold">Account active</span></label>@endunless
            </fieldset><div class="support-actions"><button class="primary-button" type="submit">{{ $target ? 'Save Changes' : 'Create User' }}</button><a class="secondary-button" href="{{ $target ? route('office.workspace.users.show', $target) : route('office.workspace.users.index') }}">Cancel</a></div>
        </form>
    </div>
</x-layouts.portal>
