@php
    $selectedRole = old('role', $target?->portalRole?->identifier ?? \App\Enums\PortalRoleIdentifier::SiteManager->value);
    $selectedCustomer = (string) old('customer_organisation_id', $target?->customer_organisation_id ?? $preselectedCustomer?->id ?? '');
    $selectedSites = array_map('strval', old('site_ids', $target?->assignedSites->pluck('id')->all() ?? ($preselectedSite ? [$preselectedSite->id] : [])));
    $returnUrl = $target ? route('office.workspace.users.show', $target) : route('office.workspace.users.index');
@endphp
<x-layouts.portal :title="($target ? 'Edit User' : 'Add User').' | Fenster'" sidebar-label="Menu">
    <div class="admin-workspace min-w-0">
        <a class="admin-back [overflow-wrap:anywhere]" href="{{ $returnUrl }}">← {{ $target?->name ?? 'Users' }}</a>
        <header><p class="eyebrow">User administration</p><h1 class="admin-title">{{ $target ? 'Edit User' : 'Add User' }}</h1><p class="admin-intro">Set up their identity, Portal role and access in one place.</p></header>
        @if ($errors->any())<div class="admin-error" role="alert"><h2 class="font-bold">Please check the form.</h2><ul class="mt-2 list-disc pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <form method="POST" action="{{ $target ? route('portal.office.users.update', $target) : route('portal.office.users.store') }}" class="min-w-0 max-w-4xl space-y-5" x-data="{ selectedRole: @js($selectedRole), selectedCustomer: @js($selectedCustomer) }">
            @csrf @if ($target) @method('PATCH') <input type="hidden" name="lock_version" value="{{ $target->lock_version }}"> @endif
            <section class="rounded-xl border border-slate-200 bg-white p-5 sm:p-6" aria-labelledby="identity-heading">
                <h2 id="identity-heading" class="section-title">Identity</h2><p class="mt-1 text-sm leading-6 text-slate-600">The name and email used for this Portal account.</p>
                <div class="mt-5 grid gap-5 sm:grid-cols-2">
                    <div class="min-w-0"><label class="form-label" for="user-name">Name</label><input class="form-input min-w-0" id="user-name" name="name" required maxlength="255" autocomplete="name" value="{{ old('name', $target?->name) }}" aria-invalid="{{ $errors->has('name') ? 'true' : 'false' }}" @if($errors->has('name')) aria-describedby="name-error" @endif>@include('office.users.field-error', ['field' => 'name', 'id' => 'name-error'])</div>
                    <div class="min-w-0"><label class="form-label" for="user-email">Email</label><input class="form-input min-w-0" id="user-email" name="email" type="email" required maxlength="255" autocomplete="email" value="{{ old('email', $target?->email) }}" aria-invalid="{{ $errors->has('email') ? 'true' : 'false' }}" @if($errors->has('email')) aria-describedby="email-error" @endif>@include('office.users.field-error', ['field' => 'email', 'id' => 'email-error'])</div>
                </div>
            </section>
            <section id="user-access" class="scroll-mt-24 rounded-xl border border-slate-200 bg-white p-5 sm:p-6" aria-labelledby="access-heading">
                <h2 id="access-heading" class="section-title">Role &amp; access</h2><p class="mt-1 text-sm leading-6 text-slate-600">External users belong to one customer and may have access to several sites for that customer.</p>
                <div class="mt-5"><label class="form-label" for="user-role">Role</label><select class="form-input" id="user-role" name="role" required x-model="selectedRole" aria-describedby="role-help{{ $errors->has('role') ? ' role-error' : '' }}" aria-invalid="{{ $errors->has('role') ? 'true' : 'false' }}">@foreach ($roles as $role)<option value="{{ $role->identifier }}" @selected($selectedRole === $role->identifier)>{{ $role->name }}</option>@endforeach</select><p id="role-help" class="mt-2 text-sm leading-6 text-slate-600">Site Manager, Assistant Site Manager and Finishing Foreman currently share the same site access permissions.</p>@include('office.users.field-error', ['field' => 'role', 'id' => 'role-error'])</div>
                <div x-show="selectedRole === 'fenster_office_staff'" class="mt-4 rounded-lg border border-sky-200 bg-sky-50 p-4"><h3 class="font-bold text-sky-950">Global Office access</h3><p class="mt-1 text-sm leading-6 text-sky-950">Fenster Office Staff can manage all customers, sites and users. Customer and site assignments are not required.</p></div>
                <div x-show="selectedRole !== 'fenster_office_staff'" class="mt-5"><label class="form-label" for="user-customer">Customer</label><select class="form-input" id="user-customer" name="customer_organisation_id" x-model="selectedCustomer" aria-describedby="customer-help{{ $errors->has('customer_organisation_id') ? ' customer-error' : '' }}" aria-invalid="{{ $errors->has('customer_organisation_id') ? 'true' : 'false' }}"><option value="">Select a customer</option>@foreach ($customers as $customer)<option value="{{ $customer->id }}" @selected($selectedCustomer === (string) $customer->id)>{{ $customer->name }}{{ $customer->is_active ? '' : ' — inactive' }}</option>@endforeach</select><p id="customer-help" class="mt-2 text-sm leading-6 text-slate-600">Choose the customer first. Only their sites can be assigned.</p>@include('office.users.field-error', ['field' => 'customer_organisation_id', 'id' => 'customer-error'])</div>
                <fieldset x-show="selectedRole !== 'fenster_office_staff'" class="mt-5 min-w-0 space-y-3" aria-describedby="sites-help{{ $errors->has('site_ids') ? ' sites-error' : '' }}"><legend class="form-label">Assigned Sites</legend><p id="sites-help" class="text-sm leading-6 text-slate-600">Choose every site this user needs. Uncheck a site to remove access. Leaving all unchecked gives the user no site access.</p>
                    <p x-show="!selectedCustomer" class="rounded-lg bg-slate-50 p-4 text-sm text-slate-600">Select a customer to see available sites.</p>
                    @foreach ($customers as $customer)
                        <div x-show="selectedCustomer === '{{ $customer->id }}'" class="rounded-lg border border-slate-200 p-3"><h3 class="font-semibold text-slate-900 [overflow-wrap:anywhere]">{{ $customer->name }}</h3>@unless ($customer->is_active)<p class="mt-1 text-sm text-amber-900">Customer inactive — site access will remain paused.</p>@endunless
                            <div class="mt-3 grid max-h-96 gap-2 overflow-y-auto sm:grid-cols-2">@forelse ($sites->where('customer_organisation_id', $customer->id) as $site)<label class="flex min-h-12 min-w-0 cursor-pointer items-start gap-3 rounded-lg border border-slate-200 px-3 py-3 hover:bg-slate-50"><input class="mt-0.5 h-5 w-5 shrink-0 rounded focus:ring-2 focus:ring-sky-600 focus:ring-offset-2" type="checkbox" name="site_ids[]" value="{{ $site->id }}" :disabled="selectedCustomer !== '{{ $customer->id }}' || selectedRole === 'fenster_office_staff'" @checked(in_array((string) $site->id, $selectedSites, true))><span class="min-w-0 text-sm leading-6 [overflow-wrap:anywhere]">{{ $site->name }}{{ $site->is_active ? '' : ' — inactive' }}</span></label>@empty<p class="text-sm leading-6 text-slate-600">No sites exist for this customer.</p>@endforelse</div>
                        </div>
                    @endforeach
                    @include('office.users.field-error', ['field' => 'site_ids', 'id' => 'sites-error'])
                </fieldset>
                @if ($target && $target->customer_organisation_id)<label x-show="(selectedRole === 'fenster_office_staff' && @js($target->portalRole?->identifier !== 'fenster_office_staff')) || (selectedRole !== 'fenster_office_staff' && selectedCustomer !== '{{ $target->customer_organisation_id }}')" class="mt-5 flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950"><input class="mt-1 h-5 w-5 shrink-0" type="checkbox" name="confirm_customer_change" value="1" @checked(old('confirm_customer_change'))><span><strong>Confirm customer change.</strong> Changing this user’s customer will remove access to sites belonging to the current customer.</span></label>@include('office.users.field-error', ['field' => 'confirm_customer_change', 'id' => 'customer-change-error'])@endif
            </section>
            <section class="rounded-xl border border-slate-200 bg-white p-5 sm:p-6" aria-labelledby="password-heading">
                <h2 id="password-heading" class="section-title">{{ $target ? 'Password (optional)' : 'Sign-in details' }}</h2><p id="password-help" class="mt-1 text-sm leading-6 text-slate-600">{{ $target ? 'Leave both fields blank to keep the current password. ' : '' }}At least 12 characters with letters and numbers. Passwords are securely hashed and never shown again.</p>
                <div class="mt-5 grid gap-5 sm:grid-cols-2"><div class="min-w-0"><label class="form-label" for="user-password">{{ $target ? 'New password (optional)' : 'Temporary password' }}</label><input class="form-input min-w-0" id="user-password" name="password" type="password" {{ $target ? '' : 'required' }} minlength="12" autocomplete="new-password" aria-describedby="password-help{{ $errors->has('password') ? ' password-error' : '' }}" aria-invalid="{{ $errors->has('password') ? 'true' : 'false' }}">@include('office.users.field-error', ['field' => 'password', 'id' => 'password-error'])</div><div class="min-w-0"><label class="form-label" for="user-password-confirmation">Confirm password</label><input class="form-input min-w-0" id="user-password-confirmation" name="password_confirmation" type="password" {{ $target ? '' : 'required' }} autocomplete="new-password"></div></div>
                @unless ($target)<div class="mt-5 border-t border-slate-100 pt-4"><input type="hidden" name="is_active" value="0"><label class="flex min-h-11 items-center gap-3"><input class="h-5 w-5 rounded" type="checkbox" name="is_active" value="1" @checked(old('is_active', true))><span class="font-semibold">Account active</span></label></div>@endunless
            </section>
            <div class="flex flex-col gap-3 sm:flex-row"><button class="primary-button" type="submit">{{ $target ? 'Save Changes' : 'Create User' }}</button><a class="secondary-button" href="{{ $returnUrl }}">Cancel</a></div>
        </form>
    </div>
</x-layouts.portal>
