<x-layouts.portal :title="$target->name.' | Users | Fenster'" sidebar-label="Menu">
    <div class="admin-workspace"><a class="admin-back" href="{{ route('office.workspace.users.index') }}">← Users</a>
        <header class="admin-page-header"><div><p class="eyebrow">User</p><h1 class="admin-title">{{ $target->name }}</h1><p class="admin-intro [overflow-wrap:anywhere]">{{ $target->email }}</p></div><div class="admin-actions"><a class="primary-button" href="{{ route('office.workspace.users.edit', $target) }}">Edit User</a><a class="admin-link-button" href="{{ route('office.workspace.users.lifecycle', $target) }}">{{ $target->is_active ? 'Deactivate' : 'Reactivate' }}</a></div></header>
        @include('office.partials.feedback')
        @if (! $target->is_active)<div class="admin-notice">This account is inactive and cannot sign in. Its customer, site assignments and history are retained.</div>@endif
        @if ($target->isSiteRole() && $target->assignedSites->isEmpty())<div class="admin-notice"><strong>No sites assigned</strong> — this user currently has no site access.</div>@endif
        <dl class="admin-card grid grid-cols-1 gap-5 sm:grid-cols-2"><div><dt class="admin-term">Role</dt><dd class="admin-value">{{ $target->portalRole?->name ?? 'Unavailable' }}</dd></div><div><dt class="admin-term">Status</dt><dd class="mt-2">@include('office.partials.status', ['active' => $target->is_active])</dd></div><div><dt class="admin-term">Customer</dt><dd class="admin-value">@if($target->customerOrganisation)<a class="admin-text-link" href="{{ route('office.workspace.customers.show', $target->customerOrganisation) }}">{{ $target->customerOrganisation->name }}</a>@else Not applicable for Office Staff @endif</dd></div><div><dt class="admin-term">Assigned sites</dt><dd class="admin-value">{{ $target->assignedSites->count() }}</dd></div></dl>
        <section><h2 class="section-title">Assigned Sites</h2><div class="admin-card-grid mt-4">@forelse($target->assignedSites as $site)<article class="admin-card"><div class="flex items-start justify-between gap-3"><h3 class="admin-card-title"><a class="admin-text-link" href="{{ route('office.workspace.sites.show', [$site->customerOrganisation, $site]) }}">{{ $site->name }}</a></h3>@include('office.partials.status', ['active' => $site->is_active && $site->customerOrganisation->is_active])</div><p class="mt-2 text-sm text-slate-600">{{ $site->customerOrganisation->name }}</p></article>@empty<div class="empty-state"><p>No sites assigned — this user currently has no site access.</p></div>@endforelse</div></section>
        <section><h2 class="section-title">Activity</h2><div class="mt-4 space-y-3">@forelse($audits as $audit)<article class="admin-card"><p class="font-bold">{{ Str::headline($audit->action->value) }}</p><p class="mt-1 text-sm text-slate-600">{{ $audit->actor_name }} · {{ $audit->occurred_at->format('j M Y, H:i') }}</p></article>@empty<div class="empty-state"><p>No account-management activity recorded yet.</p></div>@endforelse</div>{{ $audits->links() }}</section>
    </div>
</x-layouts.portal>
