<style>
.site-workspace{overflow-wrap:anywhere}
.site-workspace summary{min-height:44px}
.site-workspace{--sw-ink:#131a46;--sw-muted:#586a91;--sw-line:#dfe7f5;color:var(--sw-ink);background:linear-gradient(135deg,#f9fbff,#f0f5fc);padding:28px clamp(14px,2.4vw,34px) 36px;min-height:calc(100vh - 64px);line-height:1.5}
.site-workspace *{min-width:0}.site-workspace h1,.site-workspace h2,.site-workspace h3,.site-workspace p{margin:0}.site-workspace a{text-decoration:none}.site-workspace :is(a,button,input,select,summary):focus-visible{outline:3px solid #075bed;outline-offset:3px}
.site-workspace .sw-back{display:inline-flex;align-items:center;min-height:44px;color:#385aa0;font-size:13px;margin-bottom:8px}
.site-workspace .sw-header{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:20px}
.site-workspace h1{font-size:clamp(27px,3vw,36px);font-weight:750;letter-spacing:-.8px;line-height:1.2;overflow-wrap:anywhere}
.site-workspace .sw-customer{font-size:17px;color:#3a5182;margin-top:6px;overflow-wrap:anywhere}.site-workspace .sw-muted{color:var(--sw-muted);font-size:13px;overflow-wrap:anywhere}
.site-workspace .sw-actions{display:flex;flex-wrap:wrap;gap:9px;align-items:center}.site-workspace .sw-button{display:inline-flex;align-items:center;justify-content:center;gap:8px;min-height:44px;padding:10px 15px;border:1px solid #bfd1f0;border-radius:8px;background:#fff;color:#0755cb;font-size:13px;font-weight:700}
.site-workspace .sw-primary{background:#075bec;color:#fff;border-color:#075bec;box-shadow:0 3px 8px #075bec20}.site-workspace .sw-button:hover{filter:brightness(.96)}.site-workspace .sw-button:disabled{opacity:.5;cursor:not-allowed}
.site-workspace .sw-badge{display:inline-flex;align-items:center;gap:5px;border-radius:7px;padding:4px 8px;font-size:11px;font-weight:700;background:#edf2fa;color:#45587c;overflow-wrap:anywhere}
.site-workspace .sw-active{background:#def8ed;color:#08734b}.site-workspace .sw-attention{background:#fff0da;color:#924500}.site-workspace .sw-amendment{background:#ffe7ef;color:#ab2053}
.site-workspace .sw-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:20px 0}
.site-workspace .sw-metric{border:1px solid var(--sw-line);border-radius:12px;padding:16px 19px;background:#fff}.site-workspace .sw-metric dt{font-size:12px;color:var(--sw-muted);font-weight:650}.site-workspace .sw-metric dd{font-size:25px;font-weight:750;line-height:1.3;margin-top:5px}.site-workspace .sw-metric dd.sw-date-value{font-size:20px}
.site-workspace .sw-section{border:1px solid var(--sw-line);border-radius:12px;background:#fff;padding:19px;margin-top:18px}
.site-workspace .sw-section-heading{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:15px}.site-workspace h2{font-size:20px;font-weight:750;letter-spacing:-.4px}
.site-workspace .sw-section-heading>.sw-badge{flex-shrink:0;white-space:nowrap}.site-workspace details[open]>.sw-card-main .sw-chevron{transform:rotate(90deg)}
.site-workspace .sw-filters{display:flex;flex-wrap:wrap;gap:12px;align-items:end;margin:16px 0}.site-workspace .sw-field{flex:1 1 170px}.site-workspace label{font-size:12px;font-weight:700}.site-workspace input[type=search],.site-workspace select{display:block;width:100%;min-height:44px;margin-top:5px;border:1px solid #c9d5e9;border-radius:8px;background:#fff;padding:10px 12px;font-size:14px}
.site-workspace .sw-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:16px;align-items:start}
.site-workspace .sw-card{border:1px solid #d9e4f4;background:#fff;border-radius:11px;overflow-wrap:anywhere;box-shadow:0 3px 8px #16357005}.site-workspace .sw-card-needs{border-color:#efb7ca}
.site-workspace .sw-card-main{display:block;padding:18px;color:var(--sw-ink);border-radius:10px;min-height:44px;cursor:pointer}.site-workspace .sw-card-main:hover{background:#f7faff}.site-workspace summary.sw-card-main{list-style:none}.site-workspace summary.sw-card-main::-webkit-details-marker{display:none}
.site-workspace .sw-card-top{display:flex;align-items:start;justify-content:space-between;gap:8px;margin-bottom:13px}.site-workspace .sw-plot-title{font-size:21px;font-weight:750;letter-spacing:-.4px}.site-workspace .sw-chevron{color:#075bec;font-size:24px;line-height:1.2}
.site-workspace .sw-products{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:14px 0}.site-workspace .sw-product{display:flex;align-items:center;gap:9px;padding:10px;background:#f1f6fe;border-radius:8px}.site-workspace .sw-product svg{width:23px;height:25px;flex-shrink:0;color:#075bec}.site-workspace .sw-product-name{display:block;font-size:11px;color:#506384}.site-workspace .sw-quantity{display:block;font-size:19px;line-height:1.3;font-weight:750}.site-workspace .sw-quantity.sw-unknown{font-size:12px}
.site-workspace .sw-services{display:block;border-top:1px solid var(--sw-line);padding-top:8px}.site-workspace .sw-service{display:flex;flex-wrap:wrap;justify-content:space-between;gap:2px 8px;padding:5px 0;font-size:11px}.site-workspace .sw-service-name{font-weight:700}.site-workspace .sw-service-state{color:#546384;text-align:right}
.site-workspace .sw-card-date{display:block;margin-top:10px;padding-top:10px;border-top:1px solid var(--sw-line);font-size:12px;color:#405b89}.site-workspace .sw-card-date strong{display:block;color:#152751}
.site-workspace .sw-card-link{display:block;margin-top:12px;color:#075bec;font-size:12px;font-weight:700}
.site-workspace .sw-card-controls{border-top:1px solid var(--sw-line);padding:10px 16px;display:flex;align-items:center;justify-content:space-between;gap:8px}.site-workspace .sw-select{display:flex;align-items:center;gap:9px;min-height:44px;cursor:pointer}.site-workspace .sw-select input{width:19px;height:19px}
.site-workspace .sw-source{border-top:1px solid var(--sw-line);padding:0 16px;color:var(--sw-muted);font-size:12px}.site-workspace .sw-source summary,.site-workspace .sw-disclosure>summary{min-height:44px;display:flex;align-items:center;cursor:pointer;font-weight:700}.site-workspace .sw-source code{display:block;overflow-wrap:anywhere;padding:8px;background:#f4f7fc;margin-bottom:12px}.site-workspace .sw-disclosure{margin-top:16px}.site-workspace .sw-disclosure>summary{color:#385a92;gap:8px}
.site-workspace .sw-upcoming{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;list-style:none;padding:0;margin:0}.site-workspace .sw-upcoming a{display:flex;gap:11px;align-items:center;min-height:72px;padding:12px;background:#f5f8fd;border-radius:9px;color:var(--sw-ink);font-size:12px;overflow-wrap:anywhere}.site-workspace .sw-upcoming strong{display:block}.site-workspace .sw-date-tile{width:43px;min-width:43px;text-align:center;background:#e7effb;border-radius:8px;padding:6px;font-size:11px}.site-workspace .sw-date-tile b{display:block;font-size:19px}
.site-workspace .sw-selection{display:flex;flex-wrap:wrap;justify-content:space-between;align-items:center;gap:12px;background:#edf4ff;border:1px solid #c9dcfb;padding:12px;border-radius:10px;margin-top:16px;font-size:13px}
.site-workspace .sw-tabs{display:flex;flex-wrap:wrap;gap:8px;margin:18px 0}.site-workspace .sw-tabs a{display:inline-flex;align-items:center;min-height:44px;padding:9px 14px;border-radius:8px;color:#4d618a;background:#fff;border:1px solid var(--sw-line);font-size:13px;font-weight:650}.site-workspace .sw-tabs a[aria-current]{background:#075bec;color:#fff;border-color:#075bec}
@media(max-width:1150px){.site-workspace .sw-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.site-workspace .sw-header{flex-direction:column}.site-workspace .sw-upcoming{grid-template-columns:1fr}.site-workspace .sw-upcoming a{min-height:64px}}
@media(max-width:600px){.site-workspace{padding:20px 14px}.site-workspace .sw-summary{gap:8px;grid-template-columns:1fr 1fr}.site-workspace .sw-metric{padding:13px}.site-workspace .sw-metric:last-child{grid-column:1/-1}.site-workspace .sw-grid{grid-template-columns:1fr}.site-workspace .sw-section{padding:14px}.site-workspace .sw-actions{width:100%}.site-workspace .sw-actions a{flex:1 1 120px}.site-workspace .sw-card-main{padding:15px}.site-workspace .sw-section-heading{align-items:start}.site-workspace .sw-section-heading h2{font-size:19px}.site-workspace .sw-filters{gap:9px}.site-workspace .sw-field{flex-basis:100%}}
</style>
