<x-layouts.portal title="Review Call Off | Fenster Customer Portal">
    <section class="mx-auto max-w-6xl px-4 py-7 sm:px-6 lg:px-8" aria-labelledby="page-title">
        <div class="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><p class="eyebrow">{{ $activeSite->name }}</p><h1 id="page-title" class="page-title">Review Call Off</h1><p class="page-intro">This review is secured to your account and this active site. Submit only if these details are correct.</p></div><a href="{{ route('portal.call-offs.create') }}" class="secondary-button">Start again</a></div>
        <div class="mt-8 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-lg font-bold text-slate-950">{{ $review['request_count'] }} service {{ str('request')->plural($review['request_count']) }} will be submitted.</p>
            <div class="mt-5 space-y-3">@foreach ($review['rows'] as $row)<article class="rounded-lg border border-slate-200 p-4"><div class="flex flex-col gap-1 sm:flex-row sm:justify-between"><h2 class="font-bold text-slate-950">{{ $row['plot_reference'] }} · {{ App\Enums\CallOffServiceType::from($row['service'])->label() }}</h2><span class="text-sm font-semibold {{ $row['included'] ? 'text-emerald-700' : 'text-slate-600' }}">{{ $row['included'] ? 'Included' : 'Excluded' }}</span></div><p class="mt-1 text-sm text-slate-700">Requested {{ \Carbon\CarbonImmutable::parse($row['requested_date'])->format('j M Y') }}@if($row['normal_earliest_date']) · Normal earliest {{ \Carbon\CarbonImmutable::parse($row['normal_earliest_date'])->format('j M Y') }}@endif</p>@if($row['is_early_exception'] && $row['included'])<p class="mt-2 text-sm text-amber-800"><strong>Early date request@if($row['service'] === App\Enums\CallOffServiceType::CavityClosers->value): {{ $row['working_days_early'] }} working {{ str('day')->plural($row['working_days_early']) }} early against the 15 working day standard@endif.</strong> Early Date Reason: {{ $row['early_reason'] }}</p>@endif <x-customer-product-summary :products="$row['products']" class="mt-2" /></article>@endforeach</div>
            <div class="mt-5"><h2 class="font-bold text-slate-900">Message to Fenster</h2><p class="mt-2 text-sm text-slate-700">{{ $review['message'] ?: 'No message provided.' }}</p></div>
        </div>
        <form method="POST" action="{{ route('portal.call-offs.store') }}" class="mt-6 flex justify-end">@csrf<input type="hidden" name="confirmation_signature" value="{{ $confirmationSignature }}"><button type="submit" class="primary-button">Confirm call-off</button></form>
    </section>
</x-layouts.portal>
