<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Remove only artefacts generated by the original Sprint 3A migration.
     *
     * Legacy call-offs have an approved/rejected/withdrawn history but no trustworthy
     * proposal or negotiation audit trail. Keeping generated rows would incorrectly
     * state that a date proposal was made or accepted.
     */
    public function up(): void
    {
        $negotiationIds = DB::table('call_off_date_proposals')
            ->where('proposal_type', 'legacy_mapped_date')
            ->pluck('call_off_date_negotiation_id');

        if ($negotiationIds->isEmpty()) {
            return;
        }

        DB::table('call_off_date_proposals')
            ->whereIn('call_off_date_negotiation_id', $negotiationIds)
            ->where('proposal_type', 'legacy_mapped_date')
            ->delete();

        DB::table('call_off_date_negotiations')
            ->whereIn('id', $negotiationIds)
            ->whereNotExists(function ($query): void {
                $query->selectRaw('1')
                    ->from('call_off_date_proposals')
                    ->whereColumn('call_off_date_proposals.call_off_date_negotiation_id', 'call_off_date_negotiations.id');
            })
            ->delete();
    }

    public function down(): void
    {
        // Do not recreate invented history on rollback.
    }
};
