@php
    $currentRevision = collect($import['revisions'])->firstWhere('current', true);
    $supersededUpload = $import['state'] === 'SUPERSEDED' || ($currentRevision && $currentRevision['uuid'] !== $import['upload']);
    $appliedSites = collect($details)->filter(fn ($detail) => $detail['receipt'] !== null)->count();
@endphp
<section class="wald-panel" aria-labelledby="import-record-title"><div class="wald-heading"><h2 class="section-title" id="import-record-title">Import record</h2><span class="wald-status">{{ $supersededUpload ? 'Superseded upload' : ($import['state'] === 'FAILED' ? 'Upload needs attention' : ($import['state'] === 'NEEDS_CLARIFICATION' ? 'Check workbook layout' : 'Current revision')) }}</span></div>
    <dl class="wald-facts"><div><dt>Uploaded by</dt><dd>{{ $uploadRecord['uploader'] }}</dd></div><div><dt>Uploaded (UTC)</dt><dd>{{ Illuminate\Support\Carbon::parse($uploadRecord['created_at'])->utc()->format('j M Y, H:i') }}</dd></div><div><dt>Applied sites</dt><dd>{{ $appliedSites }} of {{ $import['manifest']['source_count'] ?? 'the detected' }} source sites</dd></div></dl>
    @if($supersededUpload)<div class="wald-notice wald-warning"><strong>This upload has been replaced.</strong><p>Its analysis and receipts remain in history. Earlier approvals cannot apply uncommitted work from this upload. Previously applied site data has not been erased.</p>@if($currentRevision && $currentRevision['uuid'] !== $import['upload'])<a class="primary-button" href="{{ route('office.workspace.pilot-import.show', $currentRevision['uuid']) }}">Open current revision {{ $currentRevision['revision'] }}</a>@endif</div>@endif
    @if($import['failure_code'])<div class="wald-notice wald-danger" role="alert"><strong>{{ $supersededUpload ? 'This earlier upload failed its checks' : 'The workbook could not be prepared' }}</strong><p>{{ App\View\Presenters\ImportReviewPresentation::failure($import['failure_code']) }}</p><p>{{ $appliedSites ? $appliedSites.' site receipts remain recorded below. Failed checks did not partially apply another site.' : 'No site from this upload has been applied to CustomerApp.' }}</p>@if(!$supersededUpload)<p>Re-analysis is available only for an eligible selected-site analysis. For an upload that failed before site selection, correct the source and upload a fresh export. Identical bytes reopen this import.</p><a class="secondary-button" href="{{ route('office.workspace.imports') }}">Upload a corrected export</a>@endif<details><summary>Failure reference</summary>{{ $import['failure_code'] }}</details></div>@endif
    @if(!empty($uploadRecord['replacement_reason']))<p><strong>Replacement reason:</strong> {{ $uploadRecord['replacement_reason'] }}</p>@endif
    <details class="wald-disclosure"><summary>Upload identity and revision history</summary><p>Export {{ $import['export_date'] }} · {{ str($import['export_slot'])->title() }} · Revision {{ $import['revision'] }}</p><p>Import reference: {{ $import['upload'] }}</p><p>{{ $uploadRecord['workbook_available'] ? 'The private stored workbook is available and verified.' : 'The private stored workbook is unavailable or could not be verified. Retained history remains readable.' }}</p><ol class="wald-timeline">@foreach($import['revisions'] as $revision)<li><a class="secondary-button" href="{{ route('office.workspace.pilot-import.show', $revision['uuid']) }}">Revision {{ $revision['revision'] }} · {{ $revision['failure_code'] ? 'Failed / ' : '' }}{{ $revision['current'] ? 'Current' : 'Superseded' }}</a><p>{{ Illuminate\Support\Carbon::parse($revision['created_at'])->utc()->format('j M Y, H:i') }} UTC @if($revision['failure_code'])· Failed checks retained @endif</p></li>@endforeach</ol></details>
</section>
