@if($run['state'] === 'FAILED')<div class="wald-notice wald-danger" role="alert"><strong>Analysis stopped for {{ $selection['site_name'] }}</strong><p>{{ App\View\Presenters\ImportReviewPresentation::failure($run['failure_code']) }}</p><p>{{ $item['receipt'] ? 'The earlier applied receipt is retained below.' : 'No changes from this site review were applied. Apply is an all-or-nothing operation.' }}</p><details><summary>Failure reference</summary>{{ $run['failure_code'] ?? 'No reference recorded' }}</details></div>@endif
@if($ui['canReanalyse'])
    <details class="wald-disclosure" @if($ui['refresh'] || $run['state'] === 'FAILED') open @endif><summary>Re-analyse the stored workbook</summary>
        <form method="POST" action="{{ route('office.workspace.pilot-import.selections.reanalyse', [$import['upload'], $selection['uuid']]) }}" class="wald-question" x-data>@csrf<input type="hidden" name="command_uuid" value="{{ (string) Illuminate\Support\Str::uuid() }}"><h4 class="wald-subtitle">Use this same upload again</h4><p>Re-analyse import uses the existing stored workbook. You do not need to upload identical bytes again.</p><p>Wald will use the current rules for {{ $selection['site_name'] }}. The previous analysis stays in history; its preview and approval can no longer be used. Review and approve the new result before Apply.</p><label class="wald-check"><input type="checkbox" name="confirmation" value="RE-ANALYSE THIS IMPORT" required x-on:invalid="$nextTick(() => $el.scrollIntoView({ block: 'center' }))"><span>I want to create a new analysis from this same upload.</span></label><button class="secondary-button" type="submit">Re-analyse import</button></form>
    </details>
@elseif(!$item['receipt'] && ($ui['refresh'] || $run['state'] === 'FAILED' || empty($item['workbook_available'])) && in_array($run['state'], ['FAILED','UPLOADED','NEEDS_CLARIFICATION','REQUIRES_REVIEW','REVIEWED','READY_TO_COMMIT']))
    <div class="wald-notice wald-warning"><strong>Re-analysis is not available for this review.</strong><p>{{ $ui['closed'] ? 'Open the current upload revision to continue.' : (empty($item['workbook_available']) ? 'The stored workbook is unavailable or could not be verified. Upload a fresh export; identical bytes would reopen this import.' : 'No reusable analysis context is available. Correct the source and upload a fresh export.') }}</p>@if(!$ui['closed'] && empty($item['workbook_available']))<a class="secondary-button" href="{{ route('office.workspace.imports') }}">Upload a fresh export</a>@endif</div>
@endif
@if($item['analysis_history'])<details class="wald-disclosure" @if(count($item['analysis_history']) > 1) open @endif><summary>Analysis history</summary><p>Showing up to the latest 20 retained analysis generations. Only the current generation can continue through review.</p><ol class="wald-timeline">@foreach($item['analysis_history'] as $analysis)<li><strong>Analysis {{ $analysis['generation'] }} · {{ $analysis['current'] ? ($ui['closed'] ? 'Retained final analysis' : 'Current') : 'Superseded / historical' }}</strong><p>{{ Illuminate\Support\Carbon::parse($analysis['created_at'])->utc()->format('j M Y, H:i') }} UTC · {{ $analysis['manual_count'] }} Office choices · {{ $analysis['automatic_count'] }} automatic choices</p></li>@endforeach</ol></details>@endif
