<x-layouts.portal title="Weekend Pilot Review | Fenster Customer Portal" sidebar-label="Menu">
    <div class="admin-workspace">
        <a class="admin-back" href="{{ route('office.workspace.imports') }}">← Weekend Pilot Imports</a>
        <header class="mt-4 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p class="eyebrow">{{ Illuminate\Support\Carbon::parse($import['export_date'])->format('j M Y') }} · {{ str($import['export_slot'])->title() }} · Revision {{ $import['revision'] }}</p><h1 class="admin-title">One-site supervised review</h1><p class="page-intro">{{ $import['manifest']['source_count'] ?? 0 }} detected source sites. {{ $import['manifest']['included_count'] ?? 0 }} rows included; {{ $import['manifest']['excluded_count'] ?? 0 }} excluded. Review and apply each selected site explicitly.</p></div><div class="flex flex-wrap gap-2"><span class="status status-red">WEEKEND PILOT</span><span class="status status-slate">OFFICE USE ONLY</span><span class="status status-slate">ONE SITE AT A TIME</span></div></header>
        <div class="mt-5 rounded-xl border-2 border-amber-300 bg-amber-50 p-4 text-amber-950" role="status"><strong>Uploaded does not mean imported.</strong> Plots appear under a CustomerApp site only after its reviewed preview is explicitly applied. Each site below shows whether that step is complete.</div>
        @if ($errors->any())<div class="mt-5 rounded-xl border-2 border-rose-300 bg-rose-50 p-4 text-rose-950" role="alert"><p class="font-bold">The pilot stopped safely.</p><ul class="mt-2 list-disc space-y-1 pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        @if (session('status'))<div class="mt-5 rounded-xl border border-emerald-300 bg-emerald-50 p-4 font-semibold text-emerald-950" role="status">{{ session('status') }}</div>@endif
        @if ($import['failure_code'])<div class="mt-5 rounded-xl border border-rose-300 bg-rose-50 p-4 text-rose-950" role="alert">Needs attention: {{ str($import['failure_code'])->replace('_', ' ')->title() }}. No Portal data changed.</div>@endif

        @if(count($import['revisions']) > 1)<section class="admin-card mt-6" aria-labelledby="revision-history-title"><h2 id="revision-history-title" class="section-title">Revision history</h2><div class="mt-4 flex flex-wrap gap-3">@foreach($import['revisions'] as $revision)<a class="secondary-button" href="{{ route('office.workspace.pilot-import.show', $revision['uuid']) }}">Revision {{ $revision['revision'] }} · {{ $revision['current'] ? 'Current' : ($revision['state'] === 'SUPERSEDED' && $revision['failure_code'] ? 'Failed / Superseded' : str($revision['state'])->replace('_', ' ')->title()) }}</a>@endforeach</div></section>@endif

        @if ($import['state'] === 'NEEDS_CLARIFICATION')
            <form method="POST" action="{{ route('office.workspace.pilot-import.confirm-structure', $import['upload']) }}" class="mt-6 rounded-xl border-2 border-amber-300 bg-amber-50 p-5">@csrf<input type="hidden" name="command_uuid" value="{{ (string) Illuminate\Support\Str::uuid() }}"><h2 class="font-bold">Confirm detected header and site list</h2><p class="mt-2 text-sm">This confirms structure only. It does not bind a site or define business meaning.</p><label class="mt-4 flex min-h-12 items-start gap-3 font-bold"><input type="checkbox" name="confirmation" value="CONFIRM DETECTED HEADER AND SITE LIST" required class="mt-0.5 h-5 w-5"><span>I have reviewed the detected structure and site list.</span></label><button class="primary-button mt-4" type="submit">Confirm structure</button></form>
        @endif

        <section class="mt-8" aria-labelledby="detected-sites-title"><p class="eyebrow">Exact identities only</p><h2 id="detected-sites-title" class="section-title">Detected source sites</h2><p class="mt-2 text-sm text-slate-600">Bind each exact source identity once to an existing CustomerApp site. New records use CustomerCode; retained pre-CustomerCode records keep their original identity. Every plot row for that source then inherits the same site; plots are never linked one at a time.</p>
            <div class="admin-card-grid mt-5">
                @foreach(($import['sources'] ?? []) as $source)
                    @php($selected = collect($import['selections'] ?? [])->firstWhere('source_identity_hash', $source['hash'] ?? ''))
                    <article class="admin-card"><div class="flex items-start justify-between gap-3"><div><p class="eyebrow">{{ $source['rows'] ?? 0 }} selected rows</p><h3 class="admin-card-title [overflow-wrap:anywhere]">{{ ($source['identity_label'] ?? 'Source identity').' '.(($source['customer_code'] ?? null) ?: ($source['identity'] ?? 'Not recorded')) }}</h3>@if(! empty($source['legacy_pre_customer_code']))<p class="mt-2 text-sm text-slate-600">Retained pre-CustomerCode record. Its historical source identity has not been changed or reinterpreted.</p>@endif @if(! empty($source['site_name']))<p class="mt-2 text-sm"><strong>Source Site Name</strong><br>{{ $source['site_name'] }}</p>@endif</div><span class="status {{ $selected ? 'status-green' : (! empty($source['binding']) ? 'status-green' : 'status-slate') }}">{{ $selected ? 'Selected' : (! empty($source['binding']) ? 'Bound' : (! empty($source['draft']) ? 'Draft' : 'Unbound')) }}</span></div>
                        @if(in_array('SOURCE_SITE_NAME_VARIATION', $source['warnings'] ?? [], true))<div class="mt-4 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950" role="status"><strong>Site name variation:</strong> {{ implode(' · ', $source['observed_site_names'] ?? []) }}. CustomerCode remains the identity; review the descriptive names.</div>@endif
                        @if($selected)<p class="mt-4 text-sm">This source site already has a review run below. It cannot be selected twice.</p>
                        @elseif($source['binding'])<p class="mt-4 text-sm">Bound to <strong>{{ $source['binding']['site_name'] }}</strong><br>{{ $source['binding']['customer_name'] }}</p><form method="POST" action="{{ route('office.workspace.pilot-import.select', $import['upload']) }}" class="mt-4">@csrf<input type="hidden" name="source_hash" value="{{ $source['hash'] }}"><input type="hidden" name="site_uuid" value="{{ $source['binding']['site_uuid'] }}"><input type="hidden" name="command_uuid" value="{{ (string) Illuminate\Support\Str::uuid() }}"><button class="primary-button w-full" type="submit">Select this one site</button></form>
                        @elseif($source['draft'])<p class="mt-4 text-sm">Draft target: <strong>{{ $source['draft']['site_name'] }}</strong><br>{{ $source['draft']['customer_name'] }}</p><form method="POST" action="{{ route('office.workspace.pilot-import.bindings.activate', $import['upload']) }}" class="mt-4 space-y-3">@csrf @foreach(['binding'=>'uuid','version'=>'version','definition_hash'=>'definition_hash','epoch'=>'epoch','site_uuid'=>'site_uuid'] as $name=>$key)<input type="hidden" name="{{ $name }}" value="{{ $source['draft'][$key] }}">@endforeach<input type="hidden" name="command_uuid" value="{{ (string) Illuminate\Support\Str::uuid() }}"><label class="form-label" for="activate-{{ $loop->index }}">Activation reason</label><input id="activate-{{ $loop->index }}" name="reason" required maxlength="2000" class="form-input" value="Reviewed exact source-site binding."><button class="primary-button w-full" type="submit">Activate exact binding</button></form>
                        @else<form method="POST" action="{{ route('office.workspace.pilot-import.bindings.draft', $import['upload']) }}" class="mt-4 space-y-3">@csrf<input type="hidden" name="source_hash" value="{{ $source['hash'] }}"><input type="hidden" name="command_uuid" value="{{ (string) Illuminate\Support\Str::uuid() }}"><label class="form-label" for="site-{{ $loop->index }}">Existing active Portal site</label><select id="site-{{ $loop->index }}" name="site_uuid" required class="form-input"><option value="">Choose a site</option>@foreach($sites as $site)<option value="{{ $site->uuid }}">{{ $site->customer_name }} · {{ $site->name }}</option>@endforeach</select><label class="form-label" for="reason-{{ $loop->index }}">Draft reason</label><input id="reason-{{ $loop->index }}" name="reason" required maxlength="2000" class="form-input" value="Exact source identity reviewed against Portal site."><button class="secondary-button w-full" type="submit">Save binding draft</button></form>@endif
                    </article>
                @endforeach
            </div>
        </section>

        @if($import['selections'])<section class="mt-9" aria-labelledby="reviews-title"><p class="eyebrow">Independent atomic review</p><h2 id="reviews-title" class="section-title">Selected site reviews</h2><div class="mt-5 space-y-6">
            @foreach($import['selections'] as $selection) @php($item = $details[$selection['uuid']]) @php($run = $item['run'])
                <article class="admin-card" id="selection-{{ $selection['uuid'] }}"><div class="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><p class="eyebrow">Exact source-to-site target</p><h3 class="admin-card-title">{{ $selection['customer_name'] }} · {{ $selection['site_name'] }}</h3><p class="mt-1 text-sm [overflow-wrap:anywhere]"><strong>{{ $selection['source_identity_label'] ?? 'Source identity' }}:</strong> {{ $selection['source_identity'] }}</p>@if(! empty($selection['legacy_pre_customer_code']))<p class="mt-1 text-sm text-slate-600">Retained pre-CustomerCode selection.</p>@endif</div><span class="status {{ $run['state'] === 'COMMITTED' ? 'status-green' : (in_array($run['state'], ['FAILED','NEEDS_CLARIFICATION']) ? 'status-red' : 'status-slate') }}">{{ ['UPLOADED' => 'Ready to analyse', 'ANALYSING' => 'Analysing', 'NEEDS_CLARIFICATION' => 'Needs your input', 'REQUIRES_REVIEW' => 'Ready to review', 'REVIEWED' => 'Ready to approve', 'READY_TO_COMMIT' => 'Ready to apply', 'COMMITTING' => 'Applying', 'COMMITTED' => 'Imported — applied', 'FAILED' => 'Failed', 'SUPERSEDED' => 'Superseded'][$run['state']] ?? 'Status unavailable' }}</span></div>
                    @if($run['state'] !== 'COMMITTED' && $run['state'] !== 'SUPERSEDED')<p class="mt-3 font-semibold text-amber-900">Not yet applied to CustomerApp. No plots from this review have been created or updated.</p>@endif
                    @if(($item['auto_resolved_count'] ?? 0) > 0)<p class="mt-3 text-sm text-slate-700">{{ $item['auto_resolved_count'] }} exact structural {{ \Illuminate\Support\Str::plural('choice', $item['auto_resolved_count']) }} resolved automatically and recorded in private review history.</p>@endif
                    @if($run['state'] === 'NEEDS_CLARIFICATION' && collect($item['questions'])->every(fn ($question) => $question['state'] === 'ANSWERED'))<p class="mt-3 text-sm text-amber-950">The previous analysis stopped before a reviewable preview. Continue after clarification, or start a fresh analysis. @if($run['failure_code'])Reason: {{ str($run['failure_code'])->replace('_', ' ')->title() }}.@endif</p>@endif
                    @if($item['analysis_needs_refresh'])<p class="mt-3 rounded-lg border border-amber-300 bg-amber-50 p-3 font-semibold text-amber-950" role="status">Analysis needs refreshing before this site's review can continue.</p>@endif
                    @if(in_array($run['state'], ['UPLOADED','NEEDS_CLARIFICATION']) && ! $item['analysis_needs_refresh'])<form method="POST" action="{{ route('office.workspace.pilot-import.selections.analyse', [$import['upload'], $selection['uuid']]) }}" class="mt-4">@csrf<input type="hidden" name="command_uuid" value="{{ (string) Illuminate\Support\Str::uuid() }}"><button class="secondary-button" type="submit">{{ $run['state'] === 'UPLOADED' ? 'Analyse selected site' : 'Continue after clarification' }}</button></form>@endif
                    @if($item['context_uuid'] && in_array($run['state'], ['UPLOADED','NEEDS_CLARIFICATION','REQUIRES_REVIEW','REVIEWED','READY_TO_COMMIT','FAILED']) && ! in_array($import['state'], ['SUPERSEDED','FAILED']))<form method="POST" action="{{ route('office.workspace.pilot-import.selections.reanalyse', [$import['upload'], $selection['uuid']]) }}" class="mt-4 rounded-xl border border-amber-300 bg-amber-50 p-4">@csrf<input type="hidden" name="command_uuid" value="{{ (string) Illuminate\Support\Str::uuid() }}"><p class="text-sm text-amber-950">Re-run this uploaded workbook using the current Wald rules. The previous analysis will remain in history. Any earlier preview or approval will become stale.</p><label class="mt-3 flex min-h-12 items-start gap-3 font-semibold"><input type="checkbox" name="confirmation" value="RE-ANALYSE THIS IMPORT" required class="mt-0.5 h-5 w-5"><span>I want to create a new analysis from this same upload.</span></label><button class="secondary-button mt-3" type="submit">Re-analyse import</button></form>@endif
                    @if(count($item['analysis_history']) > 1)<details class="mt-4 rounded-lg border border-slate-200 p-3"><summary class="cursor-pointer font-semibold">Analysis history</summary><ol class="mt-3 space-y-2">@foreach($item['analysis_history'] as $analysis)<li class="text-sm">Analysis {{ $analysis['generation'] }} · {{ $analysis['current'] ? 'Current' : 'Superseded' }} · {{ $analysis['manual_count'] }} Office {{ Illuminate\Support\Str::plural('choice', $analysis['manual_count']) }}, {{ $analysis['automatic_count'] }} automatic {{ Illuminate\Support\Str::plural('choice', $analysis['automatic_count']) }} · {{ Illuminate\Support\Carbon::parse($analysis['created_at'])->format('j M Y, H:i') }}</li>@endforeach</ol></details>@endif
                    @foreach($item['questions'] as $question) @if($question['state'] !== 'ANSWERED')<form method="POST" action="{{ route('office.workspace.pilot-import.selections.clarifications', [$import['upload'], $selection['uuid']]) }}" class="mt-5 rounded-xl border border-amber-300 bg-amber-50 p-4">@csrf<input type="hidden" name="context_uuid" value="{{ $item['context_uuid'] }}"><input type="hidden" name="question_uuid" value="{{ $question['uuid'] }}"><input type="hidden" name="sequence" value="{{ $question['sequence'] }}"><input type="hidden" name="command_uuid" value="{{ (string) Illuminate\Support\Str::uuid() }}"><fieldset><legend class="font-bold">Clarification: {{ str($question['key'])->after(':')->replace('_',' ')->title() }}</legend><div class="mt-3 space-y-2">@foreach($question['evidence']['candidates'] as $candidate)<label class="flex min-h-11 items-center gap-3"><input type="radio" name="candidate_id" value="{{ $candidate['id'] }}" required class="h-5 w-5"><span>{{ str($candidate['role'] ?? $candidate['canonical'] ?? 'candidate')->replace('_',' ')->title() }} @if(isset($candidate['header']))· {{ $candidate['header'] }}@endif</span></label>@endforeach</div></fieldset><label class="form-label mt-3" for="reason-{{ $question['uuid'] }}">Review reason</label><input id="reason-{{ $question['uuid'] }}" name="reason" required class="form-input" value="Reviewed against the controlled source dictionary."><button class="primary-button mt-3" type="submit">Record clarification</button></form>@endif @endforeach
                    @if($item['rows'])<div class="mt-5 overflow-x-auto"><table class="min-w-full text-left text-sm"><caption class="sr-only">Private staged rows for {{ $selection['site_name'] }}</caption><thead><tr class="border-b"><th class="p-2">Call No.</th><th class="p-2">Plot</th><th class="p-2">Target site</th><th class="p-2">Call type</th><th class="p-2">Completion</th><th class="p-2">Result</th></tr></thead><tbody>@foreach($item['rows'] as $row)<tr class="border-b border-slate-100"><td class="p-2 font-semibold">{{ $row['facts']['call_number'] }}</td><td class="p-2">{{ $row['facts']['plot'] }}</td><td class="p-2">{{ $selection['site_name'] }}</td><td class="p-2">{{ $row['provenance']['raw_call_type'] }}@if($row['facts']['call_type'] !== $row['provenance']['raw_call_type']) → {{ $row['facts']['call_type'] }}@endif</td><td class="p-2">{{ $row['facts']['complete'] ? 'Complete' : 'Outstanding' }}</td><td class="p-2">{{ $row['excluded'] ? 'Ignored by approved artifact rule' : ($row['issues'] ? 'Blocked' : 'Included') }}</td></tr>@endforeach</tbody></table></div>@endif
                    @if($run['state'] === 'REQUIRES_REVIEW' && ! $item['analysis_needs_refresh'])<form method="POST" action="{{ route('office.workspace.pilot-import.selections.preview', [$import['upload'], $selection['uuid']]) }}" class="mt-5">@csrf<input type="hidden" name="command_uuid" value="{{ (string) Illuminate\Support\Str::uuid() }}"><button class="primary-button" type="submit">Create one-site preview</button></form>@endif
                    @if($item['preview'])<div class="mt-5 rounded-xl border border-slate-300 bg-slate-50 p-4"><h4 class="font-bold">Pinned one-site preview</h4><p class="mt-2 text-sm"><strong>{{ $selection['source_identity_label'] ?? 'Source identity' }} {{ $item['preview']['payload']['projection']['target']['source']['identity'] ?? $selection['source_identity'] }}</strong>@if(($item['preview']['payload']['projection']['target']['source']['site_names'] ?? []) !== []) · Source Site Name {{ implode(' · ', $item['preview']['payload']['projection']['target']['source']['site_names']) }}@endif<br>→ CustomerApp <strong>{{ $selection['customer_name'] }} · {{ $selection['site_name'] }}</strong></p><p class="mt-2 text-sm">Blockers: {{ $item['preview']['payload']['blockers'] ? implode(', ', $item['preview']['payload']['blockers']) : 'None' }}. Changes to source, binding, knowledge, projection or time make it stale.</p>@if(($item['preview']['payload']['projection']['target']['plots'] ?? []) !== [])<div class="mt-4 overflow-x-auto"><table class="min-w-full text-left text-sm"><caption class="sr-only">Plot targets for {{ $selection['site_name'] }}</caption><thead><tr class="border-b"><th class="p-2">Plot</th><th class="p-2">CustomerApp site</th><th class="p-2">Resolution</th></tr></thead><tbody>@foreach($item['preview']['payload']['projection']['target']['plots'] as $plotReference => $resolution)<tr class="border-b border-slate-200"><td class="p-2 font-semibold">{{ $plotReference }}</td><td class="p-2">{{ $selection['customer_name'] }} · {{ $selection['site_name'] }}</td><td class="p-2">{{ $resolution === 'CREATE' ? 'Create under this site' : 'Reuse existing plot on this site' }}</td></tr>@endforeach</tbody></table></div>@endif</div>@endif
                    @if($run['state'] === 'REVIEWED' && ! $item['analysis_needs_refresh'] && $item['preview'] && $item['preview']['payload']['blockers'] === [])<form method="POST" action="{{ route('office.workspace.pilot-import.selections.approve', [$import['upload'], $selection['uuid']]) }}" class="mt-4">@csrf<input type="hidden" name="preview" value="{{ $item['preview']['uuid'] }}"><input type="hidden" name="hash" value="{{ $item['preview']['hash'] }}"><input type="hidden" name="command_uuid" value="{{ (string) Illuminate\Support\Str::uuid() }}"><button class="primary-button" type="submit">Approve this one-site preview</button></form>@endif
                    @if($run['state'] === 'READY_TO_COMMIT' && ! $item['analysis_needs_refresh'] && $item['preview'])<form method="POST" action="{{ route('office.workspace.pilot-import.selections.commit', [$import['upload'], $selection['uuid']]) }}" class="mt-5 rounded-xl border-2 border-rose-300 bg-rose-50 p-5">@csrf<input type="hidden" name="preview" value="{{ $item['preview']['uuid'] }}"><input type="hidden" name="hash" value="{{ $item['preview']['hash'] }}"><input type="hidden" name="command_uuid" value="{{ (string) Illuminate\Support\Str::uuid() }}"><h4 class="font-bold">Ready to apply this site's import</h4><p class="mt-2 text-sm">This will create or update the plots shown in the preview for {{ $selection['site_name'] }}. Other source sites will not be changed.</p><label class="mt-3 flex min-h-12 items-start gap-3 font-bold"><input type="checkbox" name="confirmation" value="COMMIT THIS ONE SITE" required class="mt-0.5 h-5 w-5"><span>I have reviewed the changes and want to apply this site's import.</span></label><button class="primary-button mt-4" type="submit">Apply to CustomerApp</button></form>@endif
                    @if($run['state'] === 'COMMITTED' && $item['receipt'])<div class="mt-5 rounded-xl border border-emerald-300 bg-emerald-50 p-4 text-emerald-950" role="status"><h4 class="font-bold">Import applied successfully</h4><p class="mt-2 text-sm">{{ $item['receipt']['counts']['applied'] ?? 0 }} source rows applied. {{ $item['receipt']['plot_counts']['created'] ?? 'Count unavailable' }} plots created; {{ $item['receipt']['plot_counts']['reused'] ?? 'count unavailable' }} plots reused.</p><div class="mt-4 flex flex-wrap gap-3"><a class="primary-button" href="{{ route('office.workspace.sites.show', ['customerOrganisation' => $selection['customer_uuid'], 'site' => $selection['site_uuid'], 'section' => 'plots']) }}">View site plots</a><a class="secondary-button" href="{{ route('office.workspace.sites.show', ['customerOrganisation' => $selection['customer_uuid'], 'site' => $selection['site_uuid'], 'section' => 'imports']) }}">View import history</a></div></div>@endif
                </article>
            @endforeach
        </div></section>@endif
    </div>
</x-layouts.portal>
