<article class="wald-panel wald-review" id="selection-{{ $selection['uuid'] }}">
    <div class="wald-heading"><div><p class="eyebrow">Reviewing this site only</p><h3 class="section-title">{{ $selection['customer_name'] }} · {{ $selection['site_name'] }}</h3><p><strong>{{ $selection['source_identity_label'] ?? 'Source identity' }}:</strong> {{ $selection['source_identity'] }}</p>@if(!empty($selection['legacy_pre_customer_code']))<p>Retained pre-CustomerCode selection.</p>@endif</div><span class="wald-status">{{ $ui['label'] }}</span></div>
    <ol class="wald-steps" aria-label="Workflow for {{ $selection['site_name'] }}">@foreach(['Upload','Link site','Analyse','Review','Approve','Apply','Applied'] as $step=>$label)<li @class(['is-current'=>$ui['step'] === $step, 'is-complete'=>$ui['step'] !== null && $step < $ui['step']]) @if($ui['step'] === $step) aria-current="step" @endif><span aria-hidden="true">{{ $step + 1 }}</span>{{ $label }}</li>@endforeach</ol>
    @if(!in_array($run['state'], ['COMMITTED','SUPERSEDED']))<p class="wald-safety">Not yet applied to CustomerApp. No plots from this review have been created or updated.</p>@endif
    @if($item['stage_summary'])
        @php($counts = $item['stage_summary'])
        <section class="wald-found" aria-label="Selected site analysis"><h4>We found {{ $counts['plots'] }} {{ Illuminate\Support\Str::plural('plot', $counts['plots']) }}</h4><p>{{ $counts['included'] }} included rows · {{ $counts['excluded'] }} ignored rows · {{ $counts['rows'] }} rows checked for this site.</p>@if($counts['customer_care'])<p>{{ $counts['customer_care'] }} Customer Care {{ Illuminate\Support\Str::plural('row', $counts['customer_care']) }} ignored (CU4).</p>@endif<p>{{ $counts['blocked'] ? $counts['blocked'].' source rows need attention.' : 'No source-row blockers.' }} Create or review the preview to check the full site changes.</p></section>
    @endif
    @if($ui['refresh'])<div class="wald-notice wald-warning" role="status"><strong>Analysis needs refreshing before this site's review can continue.</strong><p>The stored analysis uses earlier Wald rules. Re-analyse this same upload before reviewing it again.</p></div>@elseif($ui['expired'])<div class="wald-notice wald-warning" role="status"><strong>This preview has expired.</strong><p>Create a fresh preview and approve it again before applying anything.</p></div>@endif
    @if($run['state'] === 'NEEDS_CLARIFICATION' && $ui['questions'] === 0)<p class="wald-notice">The previous analysis stopped before a reviewable preview. Continue after clarification, or start a fresh analysis.</p>@endif
    @if($ui['questions'] && !$ui['closed'] && !$ui['refresh'])
        <section id="questions-{{ $selection['uuid'] }}"><h4 class="wald-subtitle">{{ $ui['questions'] }} {{ Illuminate\Support\Str::plural('question', $ui['questions']) }} before we can continue</h4>
            @foreach($item['questions'] as $question)
                @if($question['state'] !== 'ANSWERED')
                    <form method="POST" action="{{ route('office.workspace.pilot-import.selections.clarifications', [$import['upload'], $selection['uuid']]) }}" class="wald-question">@csrf<input type="hidden" name="context_uuid" value="{{ $item['context_uuid'] }}"><input type="hidden" name="question_uuid" value="{{ $question['uuid'] }}"><input type="hidden" name="sequence" value="{{ $question['sequence'] }}"><input type="hidden" name="command_uuid" value="{{ (string) Illuminate\Support\Str::uuid() }}">
                        <fieldset><legend>{{ App\View\Presenters\ImportReviewPresentation::question($question['key']) }}</legend><p>Your choice determines how Wald reads this site's rows. Check the workbook evidence before choosing; it does not approve or apply the import.</p>
                            @foreach($question['evidence']['candidates'] as $candidate)<label class="wald-choice"><input type="radio" name="candidate_id" value="{{ $candidate['id'] }}" required><span><strong>{{ $candidate['header'] ?? $candidate['canonical'] ?? str($candidate['role'] ?? 'Candidate')->replace('_',' ')->title() }}</strong>@if(isset($candidate['column']))<small>Workbook column {{ $candidate['column'] }}</small>@endif</span></label>@endforeach
                        </fieldset>
                        <details class="wald-disclosure"><summary>Workbook evidence for this question</summary><pre>{{ json_encode($question['evidence'], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) }}</pre></details>
                        @if($question['evidence']['candidates'])<label class="form-label" for="reason-{{ $question['uuid'] }}">Why is this the correct choice?</label><input id="reason-{{ $question['uuid'] }}" name="reason" required class="form-input" value="Reviewed against the controlled source dictionary."><button class="primary-button" type="submit">Record clarification</button>@else<p class="wald-notice wald-warning">No approved choice is available. The source value needs correction or an approved dictionary decision before this site can continue.</p>@endif
                    </form>
                @endif
            @endforeach
        </section>
    @endif
    @if($item['preview'])
        @php($targets = $item['preview']['payload']['projection']['target']['plots'] ?? [])
        @php($creates = count(array_filter($targets, fn ($resolution) => $resolution === 'CREATE')))
        @php($reuses = count(array_filter($targets, fn ($resolution) => $resolution === 'REUSE')))
        <section class="wald-preview" aria-labelledby="preview-{{ $selection['uuid'] }}"><p class="eyebrow">{{ $ui['closed'] || $ui['refresh'] || $ui['expired'] ? 'Retained preview · not a current approval' : 'One-site preview' }}</p><h4 id="preview-{{ $selection['uuid'] }}">Changes for {{ $selection['site_name'] }}</h4><p>{{ $selection['customer_name'] }} · {{ $selection['site_name'] }}</p>
            @if(!$ui['blockers'])<p><strong>{{ count($targets) }} plots: {{ $creates }} to create, {{ $reuses }} existing plots to reuse.</strong> Only this site's source facts will be updated. Customer requested dates, agreements and amendments remain protected.</p><p class="wald-status">No blockers in this preview</p>@else<div class="wald-notice wald-warning"><strong>This preview cannot be approved.</strong><ul>@foreach($ui['blockers'] as $blocker)<li>{{ App\View\Presenters\ImportReviewPresentation::issue($blocker) }} <details><summary>Issue reference</summary>{{ $blocker }}</details></li>@endforeach</ul></div>@endif
            @if($targets)<details class="wald-disclosure"><summary>Review {{ count($targets) }} plot targets</summary><table class="wald-table"><caption class="sr-only">Plot targets for {{ $selection['site_name'] }}</caption><thead><tr><th scope="col">Plot</th><th scope="col">Target site</th><th scope="col">Change</th></tr></thead><tbody>@foreach($targets as $plot=>$resolution)<tr><th scope="row" data-label="Plot">{{ $plot }}</th><td data-label="Target site">{{ $selection['site_name'] }}</td><td data-label="Change">{{ $resolution === 'CREATE' ? 'Create under this site' : 'Reuse existing plot on this site' }}</td></tr>@endforeach</tbody></table></details>@endif
            <details class="wald-disclosure"><summary>Preview evidence and validity</summary><p>This preview is checked again before approval and Apply. Changes to source, site links, Wald rules or existing Portal records may require a fresh review.</p><dl class="wald-facts"><div><dt>Preview</dt><dd>{{ $item['preview']['uuid'] }}</dd></div><div><dt>Expires (UTC)</dt><dd>{{ $item['preview']['expires_at'] ?? 'Not recorded' }}</dd></div><div><dt>Preview hash</dt><dd>{{ $item['preview']['hash'] }}</dd></div></dl></details>
        </section>
    @endif
    @if($item['rows'])
        <details class="wald-disclosure"><summary>Source rows, products and service evidence</summary><p>Showing the first {{ count($item['rows']) }} of {{ $item['stage_summary']['rows'] }} selected-site rows. Totals above cover the full analysis. Operational dates are source evidence only; they do not become customer requested dates.</p>
            <table class="wald-table"><caption class="sr-only">Private source evidence for {{ $selection['site_name'] }}</caption><thead><tr><th scope="col">Call No. / plot</th><th scope="col">Service / completion</th><th scope="col">Review result</th><th scope="col">Evidence</th></tr></thead><tbody>@foreach($item['rows'] as $row)<tr><th scope="row" data-label="Call No. / plot">{{ $row['facts']['call_number'] }}<span>Plot {{ $row['facts']['plot'] }}</span></th><td data-label="Service / completion">{{ $row['excluded'] ? 'Ignored row' : (App\Enums\CallOffServiceType::tryFrom($row['facts']['service'] ?? '')?->label() ?? 'No service established') }}<span>{{ $row['excluded'] ? 'No completion assertion' : ($row['facts']['complete'] === null ? 'Completion not supplied' : ($row['facts']['complete'] ? 'Source reports complete' : 'Source reports outstanding')) }}</span></td><td data-label="Review result">{{ $row['issues'] ? 'Needs attention' : ($row['excluded'] ? 'Ignored by approved rule' : 'Included') }}@foreach($row['issues'] as $issue)<p>{{ App\View\Presenters\ImportReviewPresentation::issue($issue) }}</p>@endforeach</td><td data-label="Evidence"><details><summary>Show row evidence</summary><pre>{{ json_encode(['facts'=>$row['facts'], 'issues'=>$row['issues'], 'provenance'=>$row['provenance']], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) }}</pre></details></td></tr>@endforeach</tbody></table>
        </details>
    @endif
    @if(($item['auto_resolved_count'] ?? 0) > 0)<details class="wald-disclosure"><summary>Automatic column choices</summary><p>{{ $item['auto_resolved_count'] }} exact structural choices resolved automatically and recorded in private review history.</p></details>@endif
    <div id="reanalysis-{{ $selection['uuid'] }}">@include('office.pilot-import.reanalysis')</div>
    @include('office.pilot-import.applied-result')
    @if(in_array($ui['action'], ['analyse','preview','approve','commit']))
        <form x-data id="next-{{ $selection['uuid'] }}" method="POST" action="{{ route('office.workspace.pilot-import.selections.'.$ui['action'], [$import['upload'], $selection['uuid']]) }}">@csrf<input type="hidden" name="command_uuid" value="{{ (string) Illuminate\Support\Str::uuid() }}">
            @if(in_array($ui['action'], ['approve','commit']))<input type="hidden" name="preview" value="{{ $item['preview']['uuid'] }}"><input type="hidden" name="hash" value="{{ $item['preview']['hash'] }}"><div class="wald-confirm"><h4>{{ $ui['action'] === 'approve' ? 'Approve this one-site preview' : "Ready to apply this site's import" }}</h4><p>{{ $creates }} plots will be created and {{ $reuses }} existing plots reused under {{ $selection['site_name'] }}. No other site is included in this action.</p><p>{{ $ui['action'] === 'approve' ? 'Approval records your review. No data is applied until you choose Apply to CustomerApp.' : 'Apply writes the reviewed source facts for this site as one complete operation.' }}</p>@if($ui['action'] === 'commit')<label class="wald-check"><input type="checkbox" name="confirmation" value="COMMIT THIS ONE SITE" required x-on:invalid="$nextTick(() => $el.scrollIntoView({ block: 'center' }))"><span>I have reviewed the changes and want to apply this site's import.</span></label>@endif</div>@endif
        </form>
    @endif
    @if($ui['action'])<div class="wald-action-bar" role="region" aria-label="Next action for {{ $selection['site_name'] }}"><div><strong>{{ $ui['label'] }}</strong><span>{{ $selection['site_name'] }} only</span></div>
        @if($ui['action'] === 'questions')<a class="primary-button" href="#questions-{{ $selection['uuid'] }}">Review questions</a>@elseif($ui['action'] === 'reanalyse')<a class="primary-button" href="#reanalysis-{{ $selection['uuid'] }}">Review re-analysis</a>@else<button class="primary-button" type="submit" form="next-{{ $selection['uuid'] }}">{{ ['analyse'=>($run['state'] === 'UPLOADED' ? 'Analyse selected site' : 'Continue after clarification'), 'preview'=>($ui['expired'] ? 'Create fresh preview' : 'Create one-site preview'), 'approve'=>'Approve this one-site preview', 'commit'=>'Apply to CustomerApp'][$ui['action']] }}</button>@endif
    </div>@endif
</article>
