        <section class="mt-8" aria-labelledby="detected-sites-title"><p class="eyebrow">Exact identities only</p><h2 id="detected-sites-title" class="section-title">Detected source sites</h2><p class="mt-2 text-sm text-slate-600">Wald matches exact customers and sites across this workbook. Office reviews new or conflicting relationships. Plots inherit their resolved site without individual linking.</p>
            @if(! empty($import['resolution_summary']))@php($totals = $import['resolution_summary'])<div class="mt-4 rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm" role="status"><strong>Workbook resolution:</strong> {{ $totals['total_rows'] }} rows, {{ $totals['included_rows'] }} included, {{ $totals['excluded_rows'] }} excluded. {{ $totals['source_sites'] }} source sites; {{ $totals['automatically_matched_sites'] }} match existing sites; {{ ($totals['outcomes']['EXACT_CUSTOMER_NEW_SITE'] ?? 0) }} new site proposals; {{ ($totals['outcomes']['NEW_CUSTOMER_AND_SITE'] ?? 0) }} new customer and site proposals; {{ $totals['blockers'] }} sites need review. Plots: {{ $totals['plots_reuse'] }} reuse, {{ $totals['plots_create'] }} create candidates.</div>@endif
            <div class="admin-card-grid mt-5">
                @foreach(($import['sources'] ?? []) as $source)
                    @php($selected = collect($import['selections'] ?? [])->firstWhere('source_identity_hash', $source['hash'] ?? ''))
                    <article class="admin-card"><div class="flex items-start justify-between gap-3"><div><p class="eyebrow">{{ $source['rows'] ?? 0 }} selected rows</p><h3 class="admin-card-title [overflow-wrap:anywhere]">{{ ($source['identity_label'] ?? 'Source identity').' '.(($source['customer_code'] ?? null) ?: ($source['identity'] ?? 'Not recorded')) }}</h3>@if(! empty($source['legacy_pre_customer_code']))<p class="mt-2 text-sm text-slate-600">Retained pre-CustomerCode record. Its historical source identity has not been changed or reinterpreted.</p>@endif @if(! empty($source['site_name']))<p class="mt-2 text-sm"><strong>Source Site Name</strong><br>{{ $source['site_name'] }}</p>@endif</div><span class="status {{ $selected ? 'status-green' : (! empty($source['binding']) ? 'status-green' : 'status-slate') }}">{{ $selected ? 'Selected' : (! empty($source['binding']) ? 'Bound' : (! empty($source['draft']) ? 'Draft' : 'Unbound')) }}</span></div>
                        @if(in_array('SOURCE_SITE_NAME_VARIATION', $source['warnings'] ?? [], true))<div class="mt-4 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950" role="status"><strong>Site name variation:</strong> {{ implode(' · ', $source['observed_site_names'] ?? []) }}. CustomerCode remains the identity; review the descriptive names.</div>@endif
                        @if(! empty($source['hierarchy']['customer']))<p class="mt-4 text-sm"><strong>Parsed source hierarchy:</strong> {{ $source['hierarchy']['customer'] }} → {{ $source['hierarchy']['site'] }} → {{ $source['hierarchy']['valid_rows'] }} plot rows</p>@endif
                        @php($proposal = $source['hierarchy_proposal'] ?? ['state' => 'LEGACY_SOURCE'])
                        @php($resolution = $source['resolution'] ?? ['state' => 'LEGACY_SOURCE'])
                        @if($resolution['state'] !== 'LEGACY_SOURCE')<p class="mt-2 text-sm"><strong>Resolution:</strong> {{ str_replace('_', ' ', $resolution['state']) }} · {{ $resolution['plot_count'] }} distinct plots · {{ $resolution['plots_reuse'] }} reuse · {{ $resolution['plots_create'] }} create candidates.</p>@endif
                        @if($resolution['state'] === 'SOURCE_HIERARCHY_CONFLICT')<div class="mt-3 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm" role="alert"><strong>Conflicting source hierarchy for this CustomerCode:</strong>@foreach($resolution['source_evidence'] as $variant)<p>{{ $variant['customer'] }} → {{ $variant['site'] }} (rows {{ implode(', ', $variant['rows']) }})</p>@endforeach</div>@endif
                        @php($unanswered = collect($source['hierarchy_issues'] ?? [])->filter(fn ($issue) => empty($issue['answer'])))
                        @if($unanswered->isNotEmpty() && ! in_array($import['state'], ['FAILED', 'SUPERSEDED'], true))<div class="mt-4 space-y-4 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm"><p><strong>Confirm ambiguous source values:</strong> {{ $unanswered->count() }} distinct values remain. The suggested customer and site come only from other valid rows with this CustomerCode; check all three parts against the source.</p>
                            @foreach($unanswered->take(20) as $issue)<form method="POST" action="{{ route('office.workspace.pilot-import.confirm-hierarchy', $import['upload']) }}" class="space-y-2 rounded-lg border border-amber-200 bg-white p-3">@csrf<input type="hidden" name="source_hash" value="{{ $source['hash'] }}"><input type="hidden" name="raw_hash" value="{{ $issue['hash'] }}"><input type="hidden" name="command_uuid" value="{{ (string) Illuminate\Support\Str::uuid() }}"><p><strong>Source row {{ implode(', ', $issue['rows']) }}:</strong> {{ $issue['raw'] }}</p>@if(! empty($issue['suggestion']))<p class="text-amber-900">Suggested from the exact {{ $source['customer_code'] }} pattern. The plot is read from the trailing digits; confirm the customer and site.</p>@endif<div class="grid gap-2 sm:grid-cols-3"><label>Customer<input class="form-input" name="customer" required maxlength="200" value="{{ $issue['suggestion']['customer'] ?? ($source['hierarchy']['customer'] ?? '') }}"></label><label>Site<input class="form-input" name="site" required maxlength="200" value="{{ $issue['suggestion']['site'] ?? ($source['hierarchy']['site'] ?? '') }}"></label><label>Plot reference<input class="form-input" name="plot" required maxlength="200" placeholder="e.g. 338 or Com 4" value="{{ $issue['suggestion']['plot'] ?? '' }}" @if(! empty($issue['suggestion'])) readonly @endif></label></div><button class="secondary-button" type="submit">Confirm this source value</button></form>@endforeach
                            @if($unanswered->count() > 20)<p>Confirm these values to reveal the next {{ min(20, $unanswered->count() - 20) }}.</p>@endif
                        </div>@endif
                        @if($proposal['state'] === 'NEW_CUSTOMER_FOUND')<div class="mt-4 rounded-lg border border-sky-300 bg-sky-50 p-3 text-sm" role="status"><strong>New customer and site proposal:</strong> {{ $proposal['customer'] }} → {{ $proposal['site'] }} for CustomerCode {{ $source['customer_code'] }} ({{ $resolution['rows'] }} rows, {{ $resolution['plot_count'] }} plots; examples: {{ implode(', ', $resolution['example_plots']) }}). Office approval is required. <a class="underline" href="{{ route('office.workspace.customers.create') }}">Create customer</a></div>
                        @elseif($proposal['state'] === 'NEW_SITE_FOUND')<div class="mt-4 rounded-lg border border-sky-300 bg-sky-50 p-3 text-sm" role="status"><strong>New site proposal:</strong> {{ $proposal['customer'] }} → {{ $proposal['site'] }} for CustomerCode {{ $source['customer_code'] }} ({{ $resolution['rows'] }} rows, {{ $resolution['plot_count'] }} plots; examples: {{ implode(', ', $resolution['example_plots']) }}). Office approval is required. <a class="underline" href="{{ route('office.workspace.sites.create', $proposal['customer_uuid']) }}">Create site</a></div>
                        @elseif($resolution['state'] === 'BINDING_CONFLICT')<div class="mt-4 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm" role="alert"><strong>Binding conflict:</strong> {{ str_replace('_', ' ', $resolution['reason']) }}. Source expects {{ $resolution['customer'] }} → {{ $resolution['site'] }}. @if($source['binding']) Current binding is {{ $source['binding']['customer_name'] }} → {{ $source['binding']['site_name'] }}. @endif Office review is required.</div>
                        @elseif(! in_array($proposal['state'], ['EXACT_SITE_FOUND', 'LEGACY_SOURCE'], true))<div class="mt-4 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm" role="alert"><strong>Hierarchy review required.</strong> {{ $source['hierarchy']['invalid_rows'] ?? 0 }} invalid rows; {{ $source['hierarchy']['conflicting_rows'] ?? 0 }} rows disagree on customer or site. Correct or clarify the source before selecting this site.</div>@endif
                        @if($proposal['state'] === 'EXACT_SITE_FOUND' && ! empty($source['binding']) && $source['binding']['site_uuid'] !== $proposal['site_uuid'])<div class="mt-4 rounded-lg border border-red-300 bg-red-50 p-3 text-sm" role="alert"><strong>Source binding / customer ownership conflict.</strong> Current: {{ $source['binding']['customer_name'] }} → {{ $source['binding']['site_name'] }}. Parsed: {{ $proposal['customer'] }} → {{ $proposal['site'] }}.</div>@endif
                        @if($selected)<p class="mt-4 text-sm">This source site already has a review above. It cannot be selected twice.</p>
                        @elseif(in_array($import['state'], ['FAILED','SUPERSEDED']))<p class="mt-4">This upload is retained for history. Continue from the current revision or upload a corrected export.</p>@elseif(! in_array($proposal['state'], ['EXACT_SITE_FOUND', 'LEGACY_SOURCE'], true) || (! empty($source['binding']) && $proposal['state'] === 'EXACT_SITE_FOUND' && $source['binding']['site_uuid'] !== $proposal['site_uuid']))<p class="mt-4 text-sm">Selection is paused until the source hierarchy and target agree.</p>@elseif($source['binding'])<p class="mt-4 text-sm">Bound to <strong>{{ $source['binding']['site_name'] }}</strong><br>{{ $source['binding']['customer_name'] }}</p><form method="POST" action="{{ route('office.workspace.pilot-import.select', $import['upload']) }}" class="mt-4">@csrf<input type="hidden" name="source_hash" value="{{ $source['hash'] }}"><input type="hidden" name="site_uuid" value="{{ $source['binding']['site_uuid'] }}"><input type="hidden" name="command_uuid" value="{{ (string) Illuminate\Support\Str::uuid() }}"><button class="primary-button w-full" type="submit">Select this one site</button></form>
                        @elseif($resolution['state'] === 'EXACT_CUSTOMER_EXACT_SITE' && ! $source['draft'])<p class="mt-4 text-sm">Exact match: <strong>{{ $resolution['customer'] }} → {{ $resolution['site'] }}</strong>. Selecting this site creates the audited source binding automatically.</p><form method="POST" action="{{ route('office.workspace.pilot-import.select', $import['upload']) }}" class="mt-4">@csrf<input type="hidden" name="source_hash" value="{{ $source['hash'] }}"><input type="hidden" name="site_uuid" value="{{ $resolution['site_uuid'] }}"><input type="hidden" name="command_uuid" value="{{ (string) Illuminate\Support\Str::uuid() }}"><button class="primary-button w-full" type="submit">Select this one site</button></form>
                        @elseif($source['draft'])<p class="mt-4 text-sm">Draft target: <strong>{{ $source['draft']['site_name'] }}</strong><br>{{ $source['draft']['customer_name'] }}</p><form method="POST" action="{{ route('office.workspace.pilot-import.bindings.activate', $import['upload']) }}" class="mt-4 space-y-3">@csrf @foreach(['binding'=>'uuid','version'=>'version','definition_hash'=>'definition_hash','epoch'=>'epoch','site_uuid'=>'site_uuid'] as $name=>$key)<input type="hidden" name="{{ $name }}" value="{{ $source['draft'][$key] }}">@endforeach<input type="hidden" name="command_uuid" value="{{ (string) Illuminate\Support\Str::uuid() }}"><label class="form-label" for="activate-{{ $loop->index }}">Activation reason</label><input id="activate-{{ $loop->index }}" name="reason" required maxlength="2000" class="form-input" value="Reviewed exact source-site binding."><button class="primary-button w-full" type="submit">Activate exact binding</button></form>
                        @else<form method="POST" action="{{ route('office.workspace.pilot-import.bindings.draft', $import['upload']) }}" class="mt-4 space-y-3">@csrf<input type="hidden" name="source_hash" value="{{ $source['hash'] }}"><input type="hidden" name="command_uuid" value="{{ (string) Illuminate\Support\Str::uuid() }}"><label class="form-label" for="site-{{ $loop->index }}">{{ $proposal['state'] === 'LEGACY_SOURCE' ? 'Existing active Portal site' : 'Exact parsed Portal site' }}</label><select id="site-{{ $loop->index }}" name="site_uuid" required class="form-input"><option value="">Choose a site</option>@foreach($sites as $site)@if($proposal['state'] === 'LEGACY_SOURCE' || $site->uuid === $proposal['site_uuid'])<option value="{{ $site->uuid }}">{{ $site->customer_name }} · {{ $site->name }}</option>@endif @endforeach</select><label class="form-label" for="reason-{{ $loop->index }}">Draft reason</label><input id="reason-{{ $loop->index }}" name="reason" required maxlength="2000" class="form-input" value="Exact source identity reviewed against Portal site."><button class="secondary-button w-full" type="submit">Save binding draft</button></form>@endif
                    </article>
                @endforeach
            </div>
        </section>
