        <section class="mt-8" aria-labelledby="detected-sites-title"><p class="eyebrow">Exact identities only</p><h2 id="detected-sites-title" class="section-title">Detected source sites</h2><p class="mt-2 text-sm text-slate-600">Bind each exact source identity once to an existing CustomerApp site. New records use CustomerCode; retained pre-CustomerCode records keep their original identity. Every plot row for that source then inherits the same site; plots are never linked one at a time.</p>
            <div class="admin-card-grid mt-5">
                @foreach(($import['sources'] ?? []) as $source)
                    @php($selected = collect($import['selections'] ?? [])->firstWhere('source_identity_hash', $source['hash'] ?? ''))
                    <article class="admin-card"><div class="flex items-start justify-between gap-3"><div><p class="eyebrow">{{ $source['rows'] ?? 0 }} selected rows</p><h3 class="admin-card-title [overflow-wrap:anywhere]">{{ ($source['identity_label'] ?? 'Source identity').' '.(($source['customer_code'] ?? null) ?: ($source['identity'] ?? 'Not recorded')) }}</h3>@if(! empty($source['legacy_pre_customer_code']))<p class="mt-2 text-sm text-slate-600">Retained pre-CustomerCode record. Its historical source identity has not been changed or reinterpreted.</p>@endif @if(! empty($source['site_name']))<p class="mt-2 text-sm"><strong>Source Site Name</strong><br>{{ $source['site_name'] }}</p>@endif</div><span class="status {{ $selected ? 'status-green' : (! empty($source['binding']) ? 'status-green' : 'status-slate') }}">{{ $selected ? 'Selected' : (! empty($source['binding']) ? 'Bound' : (! empty($source['draft']) ? 'Draft' : 'Unbound')) }}</span></div>
                        @if(in_array('SOURCE_SITE_NAME_VARIATION', $source['warnings'] ?? [], true))<div class="mt-4 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950" role="status"><strong>Site name variation:</strong> {{ implode(' · ', $source['observed_site_names'] ?? []) }}. CustomerCode remains the identity; review the descriptive names.</div>@endif
                        @if($selected)<p class="mt-4 text-sm">This source site already has a review above. It cannot be selected twice.</p>
                        @elseif(in_array($import['state'], ['FAILED','SUPERSEDED']))<p class="mt-4">This upload is retained for history. Continue from the current revision or upload a corrected export.</p>@elseif($source['binding'])<p class="mt-4 text-sm">Bound to <strong>{{ $source['binding']['site_name'] }}</strong><br>{{ $source['binding']['customer_name'] }}</p><form method="POST" action="{{ route('office.workspace.pilot-import.select', $import['upload']) }}" class="mt-4">@csrf<input type="hidden" name="source_hash" value="{{ $source['hash'] }}"><input type="hidden" name="site_uuid" value="{{ $source['binding']['site_uuid'] }}"><input type="hidden" name="command_uuid" value="{{ (string) Illuminate\Support\Str::uuid() }}"><button class="primary-button w-full" type="submit">Select this one site</button></form>
                        @elseif($source['draft'])<p class="mt-4 text-sm">Draft target: <strong>{{ $source['draft']['site_name'] }}</strong><br>{{ $source['draft']['customer_name'] }}</p><form method="POST" action="{{ route('office.workspace.pilot-import.bindings.activate', $import['upload']) }}" class="mt-4 space-y-3">@csrf @foreach(['binding'=>'uuid','version'=>'version','definition_hash'=>'definition_hash','epoch'=>'epoch','site_uuid'=>'site_uuid'] as $name=>$key)<input type="hidden" name="{{ $name }}" value="{{ $source['draft'][$key] }}">@endforeach<input type="hidden" name="command_uuid" value="{{ (string) Illuminate\Support\Str::uuid() }}"><label class="form-label" for="activate-{{ $loop->index }}">Activation reason</label><input id="activate-{{ $loop->index }}" name="reason" required maxlength="2000" class="form-input" value="Reviewed exact source-site binding."><button class="primary-button w-full" type="submit">Activate exact binding</button></form>
                        @else<form method="POST" action="{{ route('office.workspace.pilot-import.bindings.draft', $import['upload']) }}" class="mt-4 space-y-3">@csrf<input type="hidden" name="source_hash" value="{{ $source['hash'] }}"><input type="hidden" name="command_uuid" value="{{ (string) Illuminate\Support\Str::uuid() }}"><label class="form-label" for="site-{{ $loop->index }}">Existing active Portal site</label><select id="site-{{ $loop->index }}" name="site_uuid" required class="form-input"><option value="">Choose a site</option>@foreach($sites as $site)<option value="{{ $site->uuid }}">{{ $site->customer_name }} · {{ $site->name }}</option>@endforeach</select><label class="form-label" for="reason-{{ $loop->index }}">Draft reason</label><input id="reason-{{ $loop->index }}" name="reason" required maxlength="2000" class="form-input" value="Exact source identity reviewed against Portal site."><button class="secondary-button w-full" type="submit">Save binding draft</button></form>@endif
                    </article>
                @endforeach
            </div>
        </section>
