<form x-ref="importForm" method="POST" action="{{ route('office.workspace.pilot-import.upload') }}" enctype="multipart/form-data" class="imports-upload-form"
    x-data="{ date: @js(old('export_date', now()->format('Y-m-d'))), slot: @js(old('export_slot', 'MORNING')), slots: @js($replacementSlots), replacementConfirmed: false, get existing() { return this.slots[this.date + ':' + this.slot] ?? null }, submitImport() { this.$refs.exportDetails.open = true; if (!this.$refs.importForm.reportValidity()) return; if (this.existing && this.existing.state !== 'FAILED') { this.$refs.replacementDialog.showModal(); return } this.$refs.importForm.requestSubmit() }, confirmReplacement() { this.replacementConfirmed = true; this.$refs.replacementDialog.close(); this.$nextTick(() => this.$refs.importForm.requestSubmit()) } }">
    @csrf<input type="hidden" name="command_uuid" value="{{ (string) Illuminate\Support\Str::uuid() }}">
    <input type="hidden" name="predecessor" :value="existing?.uuid ?? ''">
    <input type="hidden" name="replacement_confirmation" :value="replacementConfirmed ? @js(App\SourceImport\Integration\PilotImportWorkflow::REPLACEMENT_CONFIRMATION) : ''">
    <div class="lg:col-span-2"><label for="workbook" class="form-label">RedZebra workbook</label><input x-ref="workbook" @change="$refs.exportDetails.open = true" id="workbook" name="workbook" type="file" accept=".xls,.xlsx,.csv" required class="form-input mt-1"><p class="mt-2 text-sm text-slate-600">XLS, XLSX or CSV, maximum 20 MB. Original filenames are never shown.</p></div>
    <details x-ref="exportDetails" class="imports-export-details"><summary>Export details and confirmation</summary><div class="imports-export-fields"><div><label for="export-date" class="form-label">Export date</label><input x-model="date" @change="replacementConfirmed = false" id="export-date" name="export_date" type="date" required value="{{ old('export_date', now()->format('Y-m-d')) }}" class="form-input mt-1"></div>
    <div><label for="export-slot" class="form-label">Export slot</label><select x-model="slot" @change="replacementConfirmed = false" id="export-slot" name="export_slot" required class="form-input mt-1"><option value="MORNING" @selected(old('export_slot') === 'MORNING')>Morning</option><option value="AFTERNOON" @selected(old('export_slot') === 'AFTERNOON')>Afternoon</option></select></div>
    <label class="lg:col-span-2 flex min-h-12 items-start gap-3 rounded-xl border border-amber-300 bg-amber-50 p-4 font-semibold text-amber-950"><input type="checkbox" name="confirmation" value="{{ App\SourceImport\Integration\ExportOrder::CONFIRMATION }}" required class="mt-0.5 h-5 w-5"><span>{{ App\SourceImport\Integration\ExportOrder::CONFIRMATION }}</span></label></div></details>
    <div x-cloak x-show="existing && existing.state === 'FAILED'" class="lg:col-span-2 rounded-xl border border-amber-300 bg-amber-50 p-4 text-amber-950" role="status"><p class="font-bold">The current revision failed.</p><p class="mt-1 text-sm">Revision <span x-text="existing?.revision"></span> will be retained and superseded automatically by this upload.</p></div>
    <div x-cloak x-show="existing && existing.state !== 'FAILED'" class="lg:col-span-2 rounded-xl border-2 border-amber-400 bg-amber-50 p-5 text-amber-950" role="alert" aria-live="polite">
        <h3 class="font-bold">An import already exists for this date and slot.</h3>
        <p class="mt-2 text-sm">Choosing Replace existing upload will ask for confirmation. Revision <span x-text="existing?.revision"></span> and its history will be retained.</p>
    </div>
    <dialog x-ref="replacementDialog" @cancel.prevent="replacementConfirmed = false; $el.close()" class="w-[min(36rem,calc(100%-2rem))] rounded-2xl border-2 border-amber-400 bg-white p-6 text-slate-950 shadow-2xl backdrop:bg-slate-950/60" aria-labelledby="replacement-dialog-title" aria-describedby="replacement-dialog-description">
        <h3 id="replacement-dialog-title" class="section-title">Replace existing upload?</h3>
        <p id="replacement-dialog-description" class="mt-3 text-sm leading-6">An import already exists for <strong x-text="date"></strong> — <strong x-text="slot.toLowerCase()"></strong>. This upload will replace the current version for this date and slot. The previous version and its history will be retained.</p>
        <div class="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" class="secondary-button" @click="replacementConfirmed = false; $refs.replacementDialog.close()">Cancel</button><button type="button" class="primary-button" @click="confirmReplacement()">Replace existing upload</button></div>
    </dialog>
    <div class="lg:col-span-2"><button class="primary-button" type="button" @click="submitImport()" x-text="existing ? (existing.state === 'FAILED' ? 'Replace failed import' : 'Replace existing upload') : 'Upload and check file'">Upload and check file</button></div>
</form>
